# Generated by Django 2.0.2 on 2018-02-25 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiator', models.CharField(choices=[('COMMAND_CENTER', 'Command Center'), ('DRONE', 'Drone')], default='COMMAND_CENTER', max_length=255)),
                ('initiate_time', models.DateTimeField()),
                ('instruction', models.CharField(choices=[('PICKUP', 'Pick Up'), ('CANCEL', 'Cancel'), ('REACHED', 'Reached'), ('UNLOADED', 'Unloaded')], default='PICKUP', max_length=255)),
                ('comments', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'command',
            },
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('INSTRUCTION_RECEIVED', 'Instruction Recieved'), ('ITEM_PICKED', 'Item Picked'), ('REACHED_ADDRESS', 'Reached Delivery Address'), ('ITEM_DELIVERED', 'Delivered Item'), ('REACHED_PARKING', 'Reached Packing Spot')], default='AVAILABLE', max_length=255)),
            ],
            options={
                'db_table': 'drone',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('item_spot', models.IntegerField()),
                ('order_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ORDERED', 'Ordered'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')], default='AVAILABLE', max_length=255)),
                ('order_date', models.DateTimeField()),
                ('address', models.CharField(max_length=255)),
                ('item_details', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='ItemDroneHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('action', models.CharField(max_length=255)),
                ('drone', models.ForeignKey(db_column='drone', on_delete=django.db.models.deletion.DO_NOTHING, to='track.Drone')),
                ('item', models.ForeignKey(db_column='item', on_delete=django.db.models.deletion.DO_NOTHING, to='track.Item')),
            ],
            options={
                'db_table': 'item_drone_history',
            },
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.IntegerField()),
                ('slot_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied')], default='AVAILABLE', max_length=255)),
                ('slot_details', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'parking_spot',
            },
        ),
        migrations.AddField(
            model_name='drone',
            name='parking_spot',
            field=models.ForeignKey(db_column='slot', on_delete=django.db.models.deletion.DO_NOTHING, to='track.ParkingSpot'),
        ),
    ]
